### 예외의 종류
1. Error
2. Checked Exception
3. Unchecked Exception

### Error
- 시스템 에러와 같은 심각한 문제
- 주로 JVM에 의해 발생, 개발자가 처리해서는 안 되는 문제들
- ex. StackOverflowError, OutOfMemoryError

### Checked Exception
- Compiler가 확인할 수 있는 예외, Compile Time Exception
- 반드시 try-catch 블럭을 사용하여 처리하거나 throws 해줘야 한다.
- 주로 비즈니스 로직상에서 에러가 발생하는 경우 사용한다.
- 호출하는 메소드가 Exception을 활용해 무엇인가 의미 있는 작업을 할 수 있다면 Checked Exception을 사용하자.
- 장점: 안정적인 소프트웨어 구현
- 단점: 모든 상위 클래스에서 try-catch 블록이나 throws를 반복적으로 사용하여 가독성을 떨어뜨리고, 과도한 코드 중복 초래, 코드의 결합도를 높인다. 
- ex. FileNotFoundException, IOException

### Unchecked Exception
- Compiler가 확인할 수 없고, 런타입에 확인되는 예외, Runtime Exception
- 일반적인 프로그래밍 에러, 이러한 예외는 선택적으로 처리할 수 있다.
- 호출하는 메소드가 Exception을 catch해 예외 상황을 해결하거나 문제를 해결할 수 없다면 Unchecked Exception을 사용하자.
- 무엇을 사용해야 하는지 명확하지 않다면 Uncheked Exception을 사용하자.
- 장점: 처리를 강제하지 않아 코드가 간결하고 가독성이 좋다. 또한 프로그램의 흐름을 중단하지 않고도 잘못된 상황을 표현할 수 있다.
- 단점: 예상치 못한 예외가 런타임에 발생하여 프로그램이 비정상으로 종료될 수 있다. 또한 잘 이해하고 있지 않다면, 적절하게 처리하지 않을 가능성이 존재한다.
- ex. ArrayIndexOutOfBoundsException, IllegalArgumentException

### 처리 방법
- try catch 블록
  + 예외가 발생할 수 있는 코드를 try 블록에 배치하고, catch 블록에서 발생하는 예외를 처리한다.
  + 예외가 발생해도 실행해야 하는 부분은 finally 블록에 배치한다. (예외 발생 여부와 관계없이 항상 실행)
```
try {
    // 예외가 발생할 가능성이 있는 코드
    File file = new File("file.txt");
    FileReader fr = new FileReader(file);
} catch (FileNotFoundException e) {
    // 예외 처리
    e.printStackTrace();
} finally {
    // 자원 해제 등의 정리 코드
    if(fr != null) {
        fr.close();
    }
}
```
- throws
  + 예외를 처리하는 것이 아닌 호출자에게 처리를 넘기는 방식
  + 호출자는 예외를 처리하거나 다시 throws로 던져야 한다.
```
public void readFile() throws FileNotFoundException {
    // 예외가 발생할 가능성이 있는 코드
    File file = new File("file.txt");
    FileReader fr = new FileReader(file);
}

```
- try-with-resources
  + 되도록이면 이 방식을 사용하는 것을 권장한다.
  + 자원을 try 블록안에 선언하면 try가 종료될 떄 자동으로 해제하여 자원을 안전하게 관리할 수 있다.
  + 예외처리의 향상: try, finally 두 곳 모두에서 예외가 발생하는 경우 finally 블록의 예외가 try의 예외를 가리는 문제가 발생할 수 있다. 하지만 이 방식은 발생한 모든 예외를 보존하고 처리한다. 또한 자원 해제에서 발생하는 예외는 suppressed 예외로 처리한다.
```
try (FileInputStream fis = new FileInputStream("file.txt")) {
    // 파일 처리 코드에서 예외 발생
    throw new Exception("try block exception");
} catch (Exception e) {
    // "try block exception"을 잡고, 자원 해제 시의 예외는 suppressed로 처리됩니다.
}

```

### 여러 개의 Exception 처리
- throw 를 이용할 시 쉼표(,)를 이용해 여러 개의 Exception을 처리할 수 있다.
- 예외들의 부모 클래스로 예외를 전달하여 한 번에 처리하는 것이 가능하다.
- catch 블록을 여러개 사용할 수 있다.
- catch 블록에서 옆과 같이 여러개를 넣을 수 있다. ex. catch (StudentNameFormatException | NoSuchElementException e)
- 예외를 처리한 후 다시 예외를 재전달(rethrow) 할 수 있다.

### Stack Trace
- e.printStackTrace()를 통해 예외의 발생 경로를 추적할 수 있다.
```
public class Main {
    public static void main(String[] args) {
        try {
            String str = null;
            System.out.println(str.length()); // 여기에서 NullPointerException 발생
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }
}
```
